permissions:
  use: 'none' #'toolswap.use'
  prefer-silk: 'none' #'toolswap.prefer-silk'
interactions:
  pickaxe:
    - HOPPER
    - LANTERN
    - FURNACE
    - ICE
    - PACKED_ICE
    - ANVIL
    - ENDER_CHEST
    - STONE_PRESSURE_PLATE
    - DAYLIGHT_DETECTOR
    - LIGHTNING_ROD
    - PISTON
    - STICKY_PISTON
    - DISPENSER
    - DROPPER
    - CRAFTER
    - OBSERVER
    - RAIL
    - CAULDRON
    - POWERED_RAIL
    - DETECTOR_RAIL
    - ACTIVATOR_RAIL
    - BELL
    - STONE
    - STONE_STAIRS
    - STONE_SLAB
    - COBBLESTONE
    - COBBLESTONE_STAIRS
    - COBBLESTONE_SLAB
    - COBBLESTONE_WALL
    - MOSSY_COBBLESTONE
    - MOSSY_COBBLESTONE_STAIRS
    - MOSSY_COBBLESTONE_SLAB
    - MOSSY_COBBLESTONE_WALL
    - SMOOTH_STONE
    - SMOOTH_STONE_SLAB
    - STONE_BRICKS
    - STONE_BRICK_STAIRS
    - STONE_BRICK_WALL
    - CRACKED_STONE_BRICKS
    - CHISELED_STONE_BRICKS
    - MOSSY_STONE_BRICKS
    - MOSSY_STONE_BRICK_STAIRS
    - MOSSY_STONE_BRICK_SLAB
    - MOSSY_STONE_BRICK_WALL
    - GRANITE
    - GRANITE_STAIRS
    - GRANITE_SLAB
    - GRANITE_WALL
    - POLISHED_GRANITE
    - POLISHED_GRANITE_SLAB
    - POLISHED_GRANITE_STAIRS
    - DIORITE
    - DIORITE_STAIRS
    - DIORITE_SLAB
    - DIORITE_WALL
    - POLISHED_DIORITE
    - POLISHED_DIORITE_SLAB
    - POLISHED_DIORITE_STAIRS
    - ANDESITE
    - ANDESITE_STAIRS
    - ANDESITE_SLAB
    - ANDESITE_WALL
    - POLISHED_ANDESITE
    - POLISHED_ANDESITE_SLAB
    - POLISHED_ANDESITE_STAIRS
    - DEEPSLATE
    - COBBLED_DEEPSLATE
    - COBBLED_DEEPSLATE_STAIRS
    - COBBLED_DEEPSLATE_SLAB
    - COBBLED_DEEPSLATE_WALL
    - CHISELED_DEEPSLATE
    - POLISHED_DEEPSLATE
    - POLISHED_DEEPSLATE_STAIRS
    - POLISHED_DEEPSLATE_SLAB
    - POLISHED_DEEPSLATE_WALL
    - DEEPSLATE_BRICKS
    - CRACKED_DEEPSLATE_BRICKS
    - DEEPSLATE_BRICK_STAIRS
    - DEEPSLATE_BRICK_SLAB
    - DEEPSLATE_BRICK_WALL
    - DEEPSLATE_TILES
    - CRACKED_DEEPSLATE_TILES
    - DEEPSLATE_TILE_STAIRS
    - DEEPSLATE_TILE_SLAB
    - DEEPSLATE_TILE_WALL
    - REINFORCED_DEEPSLATE
    - TUFF
    - TUFF_STAIRS
    - TUFF_SLAB
    - TUFF_WALL
    - CHISELED_TUFF
    - POLISHED_TUFF
    - POLISHED_TUFF_STAIRS
    - POLISHED_TUFF_SLAB
    - POLISHED_TUFF_WALL
    - TUFF_BRICKS
    - TUFF_BRICK_STAIRS
    - TUFF_BRICK_SLAB
    - TUFF_BRICK_WALL
    - CHISELED_TUFF_BRICKS
    - BRICKS
    - BRICK_STAIRS
    - BRICK_SLAB
    - BRICK_WALL
    - PACKED_MUD
    - MUD_BRICKS
    - MUD_BRICK_STAIRS
    - MUD_BRICK_SLAB
    - MUD_BRICK_WALL
    - SANDSTONE
    - SANDSTONE_STAIRS
    - SANDSTONE_SLAB
    - SANDSTONE_WALL
    - CHISELED_SANDSTONE
    - SMOOTH_SANDSTONE
    - SMOOTH_SANDSTONE_STAIRS
    - SMOOTH_SANDSTONE_SLAB
    - CUT_SANDSTONE
    - CUT_SANDSTONE_SLAB
    - RED_SANDSTONE
    - RED_SANDSTONE_SLAB
    - RED_SANDSTONE_STAIRS
    - RED_SANDSTONE_WALL
    - CHISELED_RED_SANDSTONE
    - SMOOTH_RED_SANDSTONE
    - SMOOTH_RED_SANDSTONE_STAIRS
    - SMOOTH_RED_SANDSTONE_SLAB
    - CUT_RED_SANDSTONE
    - CUT_RED_SANDSTONE_SLAB
    - MAGMA_BLOCK
    - OBSIDIAN
    - CRYING_OBSIDIAN
    - NETHERRACK
    - CRIMSON_NYLIUM
    - WARPED_NYLIUM
    - BONE_BLOCK
    - COAL_ORE
    - DEEPSLATE_COAL_ORE
    - IRON_ORE
    - DEEPSLATE_IRON_ORE
    - COPPER_ORE
    - DEEPSLATE_COPPER_ORE
    - GOLD_ORE
    - DEEPSLATE_GOLD_ORE
    - REDSTONE_ORE
    - DEEPSLATE_REDSTONE_ORE
    - EMERALD_ORE
    - DEEPSLATE_EMERALD_ORE
    - LAPIS_ORE
    - DEEPSLATE_LAPIS_ORE
    - DIAMOND_ORE
    - DEEPSLATE_DIAMOND_ORE
    - NETHER_GOLD_ORE
    - NETHER_QUARTZ_ORE
    - ANCIENT_DEBRIS
    - RAW_IRON_BLOCK
    - RAW_COPPER_BLOCK
    - RAW_GOLD_BLOCK
    - BUDDING_AMETHYST
    - AMETHYST_CLUSTER
    - PRISMARINE
    - PRISMARINE_STAIRS
    - PRISMARINE_SLAB
    - PRISMARINE_WALL
    - PRISMARINE_BRICKS
    - PRISMARINE_BRICK_STAIRS
    - PRISMARINE_BRICK_SLAB
    - DARK_PRISMARINE
    - DARK_PRISMARINE_STAIRS
    - DARK_PRISMARINE_SLAB
    - NETHERRACK
    - NETHER_BRICKS
    - CRACKED_NETHER_BRICKS
    - NETHER_BRICK_STAIRS
    - NETHER_BRICK_SLAB
    - NETHER_BRICK_WALL
    - NETHER_BRICK_FENCE
    - CHISELED_NETHER_BRICKS
    - RED_NETHER_BRICKS
    - RED_NETHER_BRICK_STAIRS
    - RED_NETHER_BRICK_SLAB
    - RED_NETHER_BRICK_WALL
    - BASALT
    - SMOOTH_BASALT
    - POLISHED_BASALT
    - BLACKSTONE
    - GILDED_BLACKSTONE
    - BLACKSTONE_STAIRS
    - BLACKSTONE_SLAB
    - BLACKSTONE_WALL
    - CHISELED_POLISHED_BLACKSTONE
    - POLISHED_BLACKSTONE
    - POLISHED_BLACKSTONE_STAIRS
    - POLISHED_BLACKSTONE_SLAB
    - POLISHED_BLACKSTONE_WALL
    - POLISHED_BLACKSTONE_PRESSURE_PLATE
    - POLISHED_BLACKSTONE_BRICKS
    - CRACKED_POLISHED_BLACKSTONE_BRICKS
    - POLISHED_BLACKSTONE_BRICK_STAIRS
    - POLISHED_BLACKSTONE_BRICK_SLAB
    - POLISHED_BLACKSTONE_BRICK_WALL
    - END_STONE
    - END_STONE_BRICKS
    - END_STONE_BRICK_STAIRS
    - END_STONE_BRICK_SLAB
    - END_STONE_BRICK_WALL
    - PURPUR_BLOCK
    - PURPUR_PILLAR
    - PURPUR_STAIRS
    - PURPUR_SLAB
    - COAL_BLOCK
    - IRON_BLOCK
    - IRON_BARS
    - IRON_DOOR
    - IRON_TRAPDOOR
    - HEAVY_WEIGHTED_PRESSURE_PLATE
    - CHAIN
    - GOLD_BLOCK
    - LIGHT_WEIGHTED_PRESSURE_PLATE
    - REDSTONE_BLOCK
    - EMERALD_BLOCK
    - LAPIS_BLOCK
    - DIAMOND_BLOCK
    - NETHERITE_BLOCK
    - QUARTZ_BLOCK
    - QUARTZ_STAIRS
    - QUARTZ_SLAB
    - CHISELED_QUARTZ_BLOCK
    - QUARTZ_BRICKS
    - QUARTZ_PILLAR
    - SMOOTH_QUARTZ
    - SMOOTH_QUARTZ_STAIRS
    - SMOOTH_QUARTZ_SLAB
    - AMETHYST_BLOCK
    - COPPER_BLOCK
    - CHISELED_COPPER
    - COPPER_GRATE
    - CUT_COPPER
    - CUT_COPPER_STAIRS
    - CUT_COPPER_SLAB
    - COPPER_DOOR
    - COPPER_TRAPDOOR
    - COPPER_BULB
    - EXPOSED_COPPER
    - EXPOSED_CHISELED_COPPER
    - EXPOSED_COPPER_GRATE
    - EXPOSED_CUT_COPPER
    - EXPOSED_CUT_COPPER_STAIRS
    - EXPOSED_CUT_COPPER_SLAB
    - EXPOSED_COPPER_DOOR
    - EXPOSED_COPPER_TRAPDOOR
    - EXPOSED_COPPER_BULB
    - WEATHERED_COPPER
    - WEATHERED_CHISELED_COPPER
    - WEATHERED_COPPER_GRATE
    - WEATHERED_CUT_COPPER
    - WEATHERED_CUT_COPPER_STAIRS
    - WEATHERED_CUT_COPPER_SLAB
    - WEATHERED_COPPER_DOOR
    - WEATHERED_COPPER_TRAPDOOR
    - WEATHERED_COPPER_BULB
    - OXIDIZED_COPPER
    - OXIDIZED_CHISELED_COPPER
    - OXIDIZED_COPPER_GRATE
    - OXIDIZED_CUT_COPPER
    - OXIDIZED_CUT_COPPER_STAIRS
    - OXIDIZED_CUT_COPPER_SLAB
    - OXIDIZED_COPPER_DOOR
    - OXIDIZED_COPPER_TRAPDOOR
    - OXIDIZED_COPPER_BULB
    - WAXED_COPPER_BLOCK
    - WAXED_CHISELED_COPPER
    - WAXED_COPPER_GRATE
    - WAXED_CUT_COPPER
    - WAXED_CUT_COPPER_STAIRS
    - WAXED_CUT_COPPER_SLAB
    - WAXED_COPPER_DOOR
    - WAXED_COPPER_TRAPDOOR
    - WAXED_COPPER_BULB
    - WAXED_EXPOSED_COPPER
    - WAXED_EXPOSED_CHISELED_COPPER
    - WAXED_EXPOSED_COPPER_GRATE
    - WAXED_EXPOSED_CUT_COPPER
    - WAXED_EXPOSED_CUT_COPPER_STAIRS
    - WAXED_EXPOSED_CUT_COPPER_SLAB
    - WAXED_EXPOSED_COPPER_DOOR
    - WAXED_EXPOSED_COPPER_TRAPDOOR
    - WAXED_EXPOSED_COPPER_BULB
    - WAXED_WEATHERED_COPPER
    - WAXED_WEATHERED_CHISELED_COPPER
    - WAXED_WEATHERED_COPPER_GRATE
    - WAXED_WEATHERED_CUT_COPPER
    - WAXED_WEATHERED_CUT_COPPER_STAIRS
    - WAXED_WEATHERED_CUT_COPPER_SLAB
    - WAXED_WEATHERED_COPPER_DOOR
    - WAXED_WEATHERED_COPPER_TRAPDOOR
    - WAXED_WEATHERED_COPPER_BULB
    - WAXED_OXIDIZED_COPPER
    - WAXED_OXIDIZED_CHISELED_COPPER
    - WAXED_OXIDIZED_COPPER_GRATE
    - WAXED_OXIDIZED_CUT_COPPER
    - WAXED_OXIDIZED_CUT_COPPER_STAIRS
    - WAXED_OXIDIZED_CUT_COPPER_SLAB
    - WAXED_OXIDIZED_COPPER_DOOR
    - WAXED_OXIDIZED_COPPER_TRAPDOOR
    - WAXED_OXIDIZED_COPPER_BULB
    - TERRACOTTA
    - WHITE_TERRACOTTA
    - LIGHT_GRAY_TERRACOTTA
    - GRAY_TERRACOTTA
    - BLACK_TERRACOTTA
    - BROWN_TERRACOTTA
    - RED_TERRACOTTA
    - ORANGE_TERRACOTTA
    - YELLOW_TERRACOTTA
    - LIME_TERRACOTTA
    - GREEN_TERRACOTTA
    - CYAN_TERRACOTTA
    - LIGHT_BLUE_TERRACOTTA
    - BLUE_TERRACOTTA
    - PURPLE_TERRACOTTA
    - MAGENTA_TERRACOTTA
    - PINK_TERRACOTTA
    - WHITE_CONCRETE
    - LIGHT_GRAY_CONCRETE
    - GRAY_CONCRETE
    - BLACK_CONCRETE
    - BROWN_CONCRETE
    - RED_CONCRETE
    - ORANGE_CONCRETE
    - YELLOW_CONCRETE
    - LIME_CONCRETE
    - GREEN_CONCRETE
    - CYAN_CONCRETE
    - LIGHT_BLUE_CONCRETE
    - BLUE_CONCRETE
    - PURPLE_CONCRETE
    - MAGENTA_CONCRETE
    - PINK_CONCRETE
    - WHITE_GLAZED_TERRACOTTA
    - LIGHT_GRAY_GLAZED_TERRACOTTA
    - GRAY_GLAZED_TERRACOTTA
    - BLACK_GLAZED_TERRACOTTA
    - BROWN_GLAZED_TERRACOTTA
    - RED_GLAZED_TERRACOTTA
    - ORANGE_GLAZED_TERRACOTTA
    - YELLOW_GLAZED_TERRACOTTA
    - LIME_GLAZED_TERRACOTTA
    - GREEN_GLAZED_TERRACOTTA
    - CYAN_GLAZED_TERRACOTTA
    - LIGHT_BLUE_GLAZED_TERRACOTTA
    - BLUE_GLAZED_TERRACOTTA
    - PURPLE_GLAZED_TERRACOTTA
    - MAGENTA_GLAZED_TERRACOTTA
    - PINK_GLAZED_TERRACOTTA
    - SHULKER_BOX
    - WHITE_SHULKER_BOX
    - LIGHT_GRAY_SHULKER_BOX
    - GRAY_SHULKER_BOX
    - BLACK_SHULKER_BOX
    - BROWN_SHULKER_BOX
    - RED_SHULKER_BOX
    - ORANGE_SHULKER_BOX
    - YELLOW_SHULKER_BOX
    - LIME_SHULKER_BOX
    - GREEN_SHULKER_BOX
    - CYAN_SHULKER_BOX
    - LIGHT_BLUE_SHULKER_BOX
    - BLUE_SHULKER_BOX
    - PURPLE_SHULKER_BOX
    - MAGENTA_SHULKER_BOX
    - PINK_SHULKER_BOX
  shovel:
    - GRASS_BLOCK
    - PODZOL
    - MYCELIUM
    - DIRT_PATH
    - DIRT
    - COARSE_DIRT
    - ROOTED_DIRT
    - MUD
    - CLAY
    - GRAVEL
    - SAND
    - RED_SAND
    - SNOW_BLOCK
    - SNOW
    - SOUL_SAND
    - SOUL_SOIL
    - WHITE_CONCRETE_POWDER
    - LIGHT_GRAY_CONCRETE_POWDER
    - GRAY_CONCRETE_POWDER
    - BLACK_CONCRETE_POWDER
    - BROWN_CONCRETE_POWDER
    - RED_CONCRETE_POWDER
    - ORANGE_CONCRETE_POWDER
    - YELLOW_CONCRETE_POWDER
    - LIME_CONCRETE_POWDER
    - GREEN_CONCRETE_POWDER
    - CYAN_CONCRETE_POWDER
    - LIGHT_BLUE_CONCRETE_POWDER
    - BLUE_CONCRETE_POWDER
    - PURPLE_CONCRETE_POWDER
    - MAGENTA_CONCRETE_POWDER
    - PINK_CONCRETE_POWDER
  axe:
    - JUKEBOX
    - NOTE_BLOCK
    - COMPOSTER
    - CHEST
    - TRAPPED_CHEST
    - BARREL
    - LECTERN
    - CRAFTING_TABLE
    - PUMPKIN
    - MELON
    - CARVED_PUMPKIN
    - JACK_O_LANTERN
    - OAK_LOG
    - OAK_WOOD
    - STRIPPED_OAK_LOG
    - STRIPPED_OAK_WOOD
    - OAK_PLANKS
    - OAK_STAIRS
    - OAK_SLAB
    - OAK_FENCE
    - OAK_FENCE_GATE
    - OAK_DOOR
    - OAK_TRAPDOOR
    - OAK_PRESSURE_PLATE
    - OAK_BUTTON
    - SPRUCE_LOG
    - SPRUCE_WOOD
    - STRIPPED_SPRUCE_LOG
    - STRIPPED_SPRUCE_WOOD
    - SPRUCE_PLANKS
    - SPRUCE_STAIRS
    - SPRUCE_SLAB
    - SPRUCE_FENCE
    - SPRUCE_FENCE_GATE
    - SPRUCE_DOOR
    - SPRUCE_TRAPDOOR
    - SPRUCE_PRESSURE_PLATE
    - SPRUCE_BUTTON
    - BIRCH_LOG
    - BIRCH_WOOD
    - STRIPPED_BIRCH_LOG
    - STRIPPED_BIRCH_WOOD
    - BIRCH_PLANKS
    - BIRCH_STAIRS
    - BIRCH_SLAB
    - BIRCH_FENCE
    - BIRCH_FENCE_GATE
    - BIRCH_DOOR
    - BIRCH_TRAPDOOR
    - BIRCH_PRESSURE_PLATE
    - BIRCH_BUTTON
    - JUNGLE_LOG
    - JUNGLE_WOOD
    - STRIPPED_JUNGLE_LOG
    - STRIPPED_JUNGLE_WOOD
    - JUNGLE_PLANKS
    - JUNGLE_STAIRS
    - JUNGLE_SLAB
    - JUNGLE_FENCE
    - JUNGLE_FENCE_GATE
    - JUNGLE_DOOR
    - JUNGLE_TRAPDOOR
    - JUNGLE_PRESSURE_PLATE
    - JUNGLE_BUTTON
    - ACACIA_LOG
    - ACACIA_WOOD
    - STRIPPED_ACACIA_LOG
    - STRIPPED_ACACIA_WOOD
    - ACACIA_PLANKS
    - ACACIA_STAIRS
    - ACACIA_SLAB
    - ACACIA_FENCE
    - ACACIA_FENCE_GATE
    - ACACIA_DOOR
    - ACACIA_TRAPDOOR
    - ACACIA_PRESSURE_PLATE
    - ACACIA_BUTTON
    - DARK_OAK_LOG
    - DARK_OAK_WOOD
    - STRIPPED_DARK_OAK_LOG
    - STRIPPED_DARK_OAK_WOOD
    - DARK_OAK_PLANKS
    - DARK_OAK_STAIRS
    - DARK_OAK_SLAB
    - DARK_OAK_FENCE
    - DARK_OAK_FENCE_GATE
    - DARK_OAK_DOOR
    - DARK_OAK_TRAPDOOR
    - DARK_OAK_PRESSURE_PLATE
    - DARK_OAK_BUTTON
    - MANGROVE_LOG
    - MANGROVE_WOOD
    - STRIPPED_MANGROVE_LOG
    - STRIPPED_MANGROVE_WOOD
    - MANGROVE_PLANKS
    - MANGROVE_STAIRS
    - MANGROVE_SLAB
    - MANGROVE_FENCE
    - MANGROVE_FENCE_GATE
    - MANGROVE_DOOR
    - MANGROVE_TRAPDOOR
    - MANGROVE_PRESSURE_PLATE
    - MANGROVE_BUTTON
    - CHERRY_LOG
    - CHERRY_WOOD
    - STRIPPED_CHERRY_LOG
    - STRIPPED_CHERRY_WOOD
    - CHERRY_PLANKS
    - CHERRY_STAIRS
    - CHERRY_SLAB
    - CHERRY_FENCE
    - CHERRY_FENCE_GATE
    - CHERRY_DOOR
    - CHERRY_TRAPDOOR
    - CHERRY_PRESSURE_PLATE
    - CHERRY_BUTTON
    - BAMBOO_BLOCK
    - STRIPPED_BAMBOO_BLOCK
    - BAMBOO_PLANKS
    - BAMBOO_MOSAIC
    - BAMBOO_STAIRS
    - BAMBOO_MOSAIC_STAIRS
    - BAMBOO_SLAB
    - BAMBOO_MOSAIC_SLAB
    - BAMBOO_FENCE
    - BAMBOO_FENCE_GATE
    - BAMBOO_DOOR
    - BAMBOO_TRAPDOOR
    - BAMBOO_PRESSURE_PLATE
    - BAMBOO_BUTTON
    - CRIMSON_STEM
    - CRIMSON_HYPHAE
    - STRIPPED_CRIMSON_STEM
    - STRIPPED_CRIMSON_HYPHAE
    - CRIMSON_PLANKS
    - CRIMSON_STAIRS
    - CRIMSON_SLAB
    - CRIMSON_FENCE
    - CRIMSON_FENCE_GATE
    - CRIMSON_DOOR
    - CRIMSON_TRAPDOOR
    - CRIMSON_PRESSURE_PLATE
    - CRIMSON_BUTTON
    - WARPED_STEM
    - WARPED_HYPHAE
    - STRIPPED_WARPED_STEM
    - STRIPPED_WARPED_HYPHAE
    - WARPED_PLANKS
    - WARPED_STAIRS
    - WARPED_SLAB
    - WARPED_FENCE
    - WARPED_FENCE_GATE
    - WARPED_DOOR
    - WARPED_TRAPDOOR
    - WARPED_PRESSURE_PLATE
    - WARPED_BUTTON
  hoe:
    - HAY_BLOCK
    - SCULK
    - SCULK_CATALYST
    - SCULK_SHRIEKER
    - SCULK_SENSOR
  shears:
    - WHITE_WOOL
    - LIGHT_GRAY_WOOL
    - GRAY_WOOL
    - BLACK_WOOL
    - BROWN_WOOL
    - RED_WOOL
    - ORANGE_WOOL
    - YELLOW_WOOL
    - LIME_WOOL
    - GREEN_WOOL
    - CYAN_WOOL
    - LIGHT_BLUE_WOOL
    - BLUE_WOOL
    - PURPLE_WOOL
    - MAGENTA_WOOL
    - PINK_WOOL